---
# tasks file for vpc

# Calling out contents in variable file

- include_vars: "vars/main.yml"
  tags: vpc-creation

# Create a vpc for the Bastion Server

- name: create a VPC
  amazon.aws.ec2_vpc_net:
    name: "{{ bastion_name }}"
    cidr_block: "{{ cidr_block }}"
    region: "{{ region }}"
    register: vpc_info