- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Start SonarQube
  ansible.builtin.systemd:
    name: sonarqube
    enabled: true
    state: started

- name: Restart Jenkins
  ansible.builtin.systemd:
    name: jenkins
    state: restarted

