region                       = "eu-central-1"
name                         = "login-page"
cidr_block                   = "10.0.0.0/16"
public_subnets               = ["10.0.1.0/24", "10.0.2.0/24"]
private_backend_subnets      = ["10.0.5.0/24", "10.0.6.0/24"]
private_frontend_subnets     = ["10.0.3.0/24", "10.0.4.0/24"] 
private_db_subnets           = ["10.0.7.0/24", "10.0.8.0/24"] 
instance_name                = "login-app"
template_name1               = "nginx-frontend-engine"
template_name2               = "tomcat-backend-engine" 
instance_ami_maven           = "ami-03250b0e01c28d196"
instance_ami_nginx           = "ami-000005bb5a100e80f"
instance_type                = "t3.micro"   
key_name                     = "java-app-key"
sg                           = "login-page-sg"
parameter_group_name         = "default.mysql8.0"
instance_class               = "db.t3.micro"
username                     = "admin"
password                     = "Admin123"  
rds-sg                       = "login-page-database"
min_size                     = 2
max_size                     = 4
desired_capacity             = 2 