variable "region" {}
variable "name" {}
variable "cidr_block" {}
variable "public_subnets" {}
variable "private_backend_subnets" {}
variable "private_db_subnets" {}
variable "template_name2" {}
variable "instance_ami_nginx" {}
variable "instance_ami_maven" {}
variable "instance_type" {}
variable "key_name" {}
variable "sg" {}
variable "parameter_group_name" {}
variable "username" {}
variable "password" {}
variable "instance_class" {}
variable "rds-sg" {}
variable "template_name1" {}
variable "instance_name" {}
variable "max_size" {}
variable "min_size" {}
variable "desired_capacity" {}
variable "private_frontend_subnets" {}