---
# tasks file for security-groups

- include_vars: "vars/main.yml"
  tags: security-group-creation

# Create security group
- name: Create security group for the ec2 instance
  amazon.aws.ec2_security_group:
    name: bastion-sg
    description: security group for my ec2
    region: "{{ region }}"
    vpc_id: "{{ vpc_info.vpc.id}}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
        rule_desc: "SSH access"

      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
        rule_desc: "HTTP access"

      - proto: tcp
        from_port: 8080
        to_port: 8080
        cidr_ip: 0.0.0.0/0
        rule_desc: "Jenkins web interface"

      - proto: tcp
        from_port: 9000
        to_port: 9000
        cidr_ip: 0.0.0.0/0
        rule_desc: "SonarQube web interface"

      - proto: tcp
        from_port: 50000
        to_port: 50000
        cidr_ip: 10.0.0.0/16
        rule_desc: jenkins-agent

      - proto: all
        from_port: -1
        to_port: -1
        cidr_ip: 0.0.0.0/0
        rule_desc: outbound      
    state: present
  register: security_group_info