---
# tasks file for install-pkg

- name: Install Java 17
  ansible.builtin.apt:
    name: "{{ java_package }}"
    state: present
  tags:
    - java


- name: Install Required Packages
  ansible.builtin.apt:
    pkg: "{{ pkg_list }}"
    state: present
  


- name: Download Terraform Binary Zip
  ansible.builtin.get_url:
    url: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
    dest: "/tmp/terraform_{{ terraform_version }}_linux_amd64.zip"
    mode: 0644
  tags:
    - terraform

- name: Unpack Terraform into /usr/local/bin
  ansible.builtin.unarchive:
    src: "/tmp/terraform_{{ terraform_version }}_linux_amd64.zip"
    dest: /usr/local/bin
    remote_src: yes
  tags:
    - terraform

- name: Ensure Terraform binary is executable
  ansible.builtin.file:
    path: /usr/local/bin/terraform
    mode: '0755'
  tags:
    - terraform

- name: Add Jenkins repository key
  ansible.builtin.get_url:
    url: "https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key"
    dest: "/usr/share/keyrings/jenkins-keyring.asc"
    mode: '0644'
    owner: root
    group: root
  tags:
    - jenkins

- name: Add Jenkins repository
  ansible.builtin.apt_repository:
    repo: " deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
    state: present
    filename: jenkins
  tags:
    - jenkins

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    
- name: Install Jenkins
  ansible.builtin.apt:
    name: jenkins
    state: latest
  notify: Start Jenkins
  tags: 
    - jenkins


- name: Download SonarQube
  ansible.builtin.get_url:
    url: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-10.3.0.82913.zip
    dest: /opt/sonarqube.zip

- name: Extract SonarQube
  ansible.builtin.unarchive:
    src: /opt/sonarqube.zip
    dest: /opt/
    remote_src: yes

- name: Rename extracted SonarQube folder
  ansible.builtin.command: mv /opt/sonarqube-10.3.0.82913 /opt/sonarqube
  args:
    creates: /opt/sonarqube

- name: Create a systemd service for SonarQube (basic setup)
  ansible.builtin.copy:
    src: sonarqube.service
    dest: /etc/systemd/system/sonarqube.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - Reload systemd
    - Start SonarQube
  