variable "template_name1" {}
variable "template_name2" {}
variable "instance_ami_maven" {}
variable "instance_ami_nginx" {}
variable "instance_type" {}
variable "key_name" {}
variable "sg" {}
variable "vpc-id" {}
variable "rds-sg" {}
variable "instance_name" {}