---
# task for ami retrieval


- include_vars: "vars/main.yml"
  tags: ami-retrieval

# Get Latest Ubuntu AMI
- name: Query AWS for the latest Ubuntu AMI
  command: aws ec2 describe-images --region "{{ region }}" --owners 099720109477 --filters "Name=name,Values=ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-*" "Name=state,Values=available" --query 'Images | sort_by(@, &CreationDate) | [-1].ImageId' --output text
  register: ami_facts
  
- name: Print the latest Ubuntu AMI ID
  debug:
    var: ami_facts.stdout